name: quotes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  equatable: ^2.0.3
  fluttertoast: ^8.0.9
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoLight.png
    - assets/images/quote.png
    - lang/ar.json
    - lang/en.json

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Bold.ttf
        - asset: assets/fonts/Product Sans Bold Italic.ttf
        - asset: assets/fonts/Product Sans Italic.ttf
        - asset: assets/fonts/Product Sans Regular.ttf
          style: italic